### PR TITLE
Load the events from the database

### PR DESCRIPTION
**Pull request by jacebrowning**

### CODE REVIEW

**Comment by jacebrowning** [comment]
@Ross-Hunter Can I get some help with this? I'm trying to populate the challenge from with events from the database, but I can't figure out how to pass the result through the form as `event_id`. There seems to be some nesting going on:

```
Parameters: {"utf8"=>"✓", "authenticity_token"=>"mP37gOvCD0LNe6bA/mKey42xKJeaqe+9QokEb419N1ly914OOhWUIqhVgYoeSzqmR5fqH8B1UbAZl2oQucbtPw==", "event"=>{"event_id"=>"3c7cba4b-f50e-4dff-bd4e-10780f933b02"}, "challengee"=>"My Friends", "emotion"=>"Sad", "stakes"=>"$20", "meme_name"=>"votestakes-barack-obama", "commit"=>"Create Challenge"}
```

**Comment by Ross-Hunter** [comment]
It looks like that is what the `collection_select` gives you. You will see a lot of demo code that relies on there being a top level object like `:challenge` in a controller and the strong_parameters will look like `params.require(:challenge).permit...`. I didn't like that so I didn't use it, but it does seem to create some issues for stuff like this. So i just loaded the options from the collection into the existing select tag.

**Comment by jacebrowning** [comment]
@Ross-Hunter Thanks! Will my change work to update the previously created challenges?

**Comment by Ross-Hunter** [comment]
You are going to have a bad time since that will happen on every migration. You should find challenges with nil events and update them, I would just do that out of band and not in a migration.

Also, I made event and creator required and so tests are failing now.

**Pull request merged**
