### PR TITLE
Add meme attributes to challenges

### LINKED ISSUE #7: Generate meme URLs from challenge model
Generate meme url for sharing
Hopefully display meme on creation screen

### PR DESCRIPTION
**Pull request by jacebrowning**
Closes #7

### CODE REVIEW

**Comment by jacebrowning** [comment]
@Ross-Hunter This was my first stab at this. Things I need your help with:
- [ ] Default `challenge.challenger` to the user's first name
- [ ] Populate the list of events from the `events` table
- [ ] Get the challenge's event name from the `event` model
- [ ] Render the meme image on the create, show, and edit pages

**Comment by Ross-Hunter** [comment]
You need to create a migration instead of editing `schema.rb` directly.

http://edgeguides.rubyonrails.org/active_record_migrations.html

**Comment by jacebrowning** [comment]
I didn't actually touch `schema.rb`. Some Rails action modified that so I assumed I needed to commit those changes. What indicates "a migration needs to be created" to you?

**Comment by Ross-Hunter** [comment]
It looks like a migration is missing. Schema.rb should be the result of running all of the migrations. Searching for the term `challengee` it shows up in `schema.rb` but not in any migrations. Did you manually add fields to the database?

**Comment by jacebrowning** [comment]
Yes.

**Comment by Ross-Hunter** [comment]
Need some of this stuff in dev, so let's merge.

**Pull request merged**
